name: movie_magic
description: A new Flutter project.

publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  carousel_slider: ^4.2.1
  postgres: ^3.0.0
  flutter_dotenv: ^5.1.0
  localstorage: ^4.0.1+4
  google_sign_in: ^6.1.6
  crypt: ^4.3.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  flutterfire_cli: ^0.1.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/


  uses-material-design: true

